version: "3.8"

x-newman-defaults: &newman_defaults
  image: postman/newman:latest
  depends_on:
    simple_app:
      condition: service_healthy
  volumes:
    - ./tests:/etc/newman/tests:rw
  working_dir: /etc/newman/tests

services:
  simple_app:
    build: .
    container_name: simple_app
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/simple_app/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  newman_create:
    <<: *newman_defaults
    container_name: newman_tests_create_user
    command:
      - run
      - simple_app.postman_collection.json
      - --environment
      - simple_app_env.postman_environment.json
      - --folder
      - create_user
      - --iteration-data
      - endpoints/create_user/test_data.json
      - --reporters
      - cli,junit
      - --reporter-junit-export
      - reports/create_user.junit.xml

  newman_get:
    <<: *newman_defaults
    container_name: newman_tests_get_user
    command:
      - run
      - simple_app.postman_collection.json
      - --environment
      - simple_app_env.postman_environment.json
      - --folder
      - get_user
      - --iteration-data
      - endpoints/get_user/test_data.json
      - --reporters
      - cli,junit
      - --reporter-junit-export
      - reports/get_user.junit.xml