services:
  simple_app:
    build: .
    container_name: simple_app
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/simple_app/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  newman:
    image: postman/newman:latest
    container_name: newman_tests
    depends_on:
      - simple_app
    volumes:
      - ./tests:/etc/newman/tests:rw
    working_dir: /etc/newman/tests
    command:
      - run
      - simple_app.postman_collection.json
      - --environment
      - simple_app_env.postman_environment.json
      - --folder
      - create_user
      - --folder
      - get_user
      - --iteration-data
      - endpoints/create_user/test_data.json
      - --iteration-data
      - endpoints/get_user/test_data.json
      - --reporters
      - cli,junit
      - --reporter-junit-export
      - reports/all_tests.junit.xml
